language: python
addons:
    postgresql: "9.4"
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=1.10.5
    - DJANGO_VERSION=1.11
install: 
    - pip install -r requirements-test.txt
    - pip install Django==$DJANGO_VERSION
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script:
    - ./run-tests.sh
after_success:
    - coveralls
